spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: statement-processor
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
